ifeq ($(EMULATOR), 1)
CC_FLAGS += -D"EMULATOR_TEST_MEMORY"=1
else
CC_FLAGS += -D"EMULATOR_TEST_MEMORY"=0
endif
ifeq ($(DECELERATION), 1)
CC_FLAGS += -D"DECELERATION_OF_TIME"=1
else
CC_FLAGS += -D"DECELERATION_OF_TIME"=0
endif
ifeq ($(ADDONS), 1)
CC_FLAGS += -D"REGTST_ADDONS"=1
else
CC_FLAGS += -D"REGTST_ADDONS"=0
endif
ifeq ($(EXIT_BANNER), 1)
CC_FLAGS += -D"ADDONS_EXIT_BANNER"=1
CC_SOURCES += addons/exit-banner/exit-banner.c
else
CC_FLAGS += -D"ADDONS_EXIT_BANNER"=0
endif
ifeq ($(PROGRESS_DUMP), 1)
CC_FLAGS += -D"ADDONS_PROGRESS_DUMP"=1
CC_SOURCES += addons/progress-dump/progress-dump.c
else
CC_FLAGS += -D"ADDONS_PROGRESS_DUMP"=0
endif
ifeq ($(REGTEST_BANNER), 1)
CC_FLAGS += -D"REGTEST_REGTEST_BANNER"=1
CC_SOURCES += addons/regtest-banner/regtest-banner.c
else
CC_FLAGS += -D"REGTEST_REGTEST_BANNER"=0
endif
ifeq ($(TARGET), DEBUG)
CC_FLAGS += -D"REGTEST_DEBUG"=1
REGTEST_DEBUG := 1
else
CC_FLAGS += -D"REGTEST_DEBUG"=0
REGTEST_DEBUG := 0
endif

TOKENS += VENDOR
TOKENS += TARGET
TOKENS += EMULATOR
TOKENS += ADDONS
TOKENS += DECELERATION
TOKENS += EXIT_BANNER
TOKENS += PROGRESS_DUMP
TOKENS += REGTEST_BANNER
TOKENS += REGTEST_DEBUG